name: app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  shared_preferences: ^2.0.0
  pointycastle: ^3.1.1
  crypto: ^3.0.3
  convert: ^3.1.1
  encrypt: ^5.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.0.16

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/images/profilepics/
    - assets/